### ISSUE TITLE
"Context" isn't really context

### ISSUE THREAD

**Issue by skerit** [IvanDimanov/paratask#1]
Your module uses the "context" property, but it actually sets the scope. As you know, context refers to "this" in JavaScript. Maybe rename that for a future version?

**Comment by IvanDimanov** [comment]
Hi @skerit 
That's indeed true. The names "fork" and "context" took me a lot to come with and I'm still not sure if they fit best.
Do you think renaming "context" => "scope" will give more sense ?

**Comment by IvanDimanov** [comment]
The suggested rename is official.
"context" is still available as an alias for possible legacy issues.
Should you have any other idea, please let me know :)
